### ISSUE TITLE
Add support for "python setup.py install" without sudo

### ISSUE THREAD

**Issue by guyluz11** [Tungsteno74/NPi.GPIO#35]
`sudo python setup.py install`
is working but without `sudo` I get missing permissions.
Running it with sudo will work on regular desktop but when I do the same inside snap that I am creating (.py file use `NPI.GPIO as GPIO`) I get an error 
`Traceback (most recent call last):
  File "/snap/mainb/x24/on.py", line 3, in <module>
    import NPi.GPIO as GPIO
ImportError: No module named 'NPi'`

And the same when using `implementing RPi.GPIO as GPIO`
(Can't recreate error, my snapcraft crashing  now lol)

I managed to recreate this in [RPi.GPIO.NP](https://github.com/chainsx/RPi.GPIO.NP) just with the  `sudo python setup.py install ` and not bouth `python setup.py install` and `sudo  python setup.py install` as they asked.

> Please be attention that you need use both python and sudo python to make the RPi.GPIO_NP work well.

**Comment by Tungsteno74** [comment]
Which platform do you use?
Which OS do you use (and version)?

**Comment by guyluz11** [comment]
This is a [snap](https://docs.snapcraft.io/getting-started) so no spesicif os for the installation because it is running in container with only the parts that I (the programmer of the SNEP) specified  (in my case it was running the snap on Ubuntu core os).
If I understand correctly snap run in confined place and can only be read only, because of this it will not work with the `sudo python setup.py install `

**Comment by Tungsteno74** [comment]
@guyluz11 
At the moment, for what i've discovered this is not a limit of NPi.GPIO. The user that run the script or python instance need to be a root or have privileges to access low level hardware components (GPIOs, etc). Thus, your OS must have an I/O or GPIO privileged group, as happens in the Raspberri Pi OS. For what i know about the Snap tool, there should be an option in your snap file config that allow you to start the script with root privileges (something like "dev" functionality).
