### ISSUE TITLE
Nanopi duo2 error

### ISSUE THREAD

**Issue by Mangix-T** [Tungsteno74/NPi.GPIO#40]
pi@NanoPi-Duo2:~$ sudo python3 npi_gpio_1.py                                      Traceback (most recent call last):
  File "npi_gpio.py", line 1, in <module>
    import NPi.GPIO as GPIO
  File "/usr/local/lib/python3.5/dist-packages/NPi.GPIO-0.5.8.6-py3.5-linux-armv7l.egg/NPi/GPIO/__init__.py", line 1, in <module>
    from NPi._GPIO import *
RuntimeError: Is not NanoPi based board.

how to fix?

**Comment by Tungsteno74** [comment]
Check if you have one of the following files and tell me what is written:
`cat etc/armbian-release`
or
`cat cat etc/friendlyelec-release`
or
`cat /sys/class/sunxi_info/sys_info`

**Comment by Mangix-T** [comment]
pi@NanoPi-Duo2:~$ cat etc/armbian-release
cat: etc/armbian-release: No such file or directory

pi@NanoPi-Duo2:~$ cat cat etc/friendlyelec-release
cat: cat: No such file or directory
cat: etc/friendlyelec-release: No such file or directory

pi@NanoPi-Duo2:~$ cat /sys/class/sunxi_info/sys_info
sunxi_platform    : sun8iw7p1
sunxi_secure      : normal
sunxi_chipid      : unsupported
sunxi_chiptype    : unsupported
sunxi_batchno     : unsupported
sunxi_board_id    : 8(0)
board_manufacturer: FriendlyElec
board_name        : FriendlyElec NanoPi-Duo2

image : "nanopi-duo2_sd_friendlycore-xenial_4.14"

**Comment by Mangix-T** [comment]
Now it solved
I change image form official to armbian

Thank you.

ในวันที่ อา. 24 พ.ย. 2019 07:29 Tungsteno74 <notifications@github.com>
เขียนว่า:

**Comment by Tungsteno74** [comment]
Yep, it is the problem. This works only with armbian version :)
